version: 2

models:
  - name: bronze_customer
    description: "This is the first layer of our data pipeline, where we pull in raw data from our source and perform basic transformations to clean and standardize it."
    columns:
      - name: customer_id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null
  - name: silver_customer
    description: "This is the first layer of our data pipeline, where we pull in raw data from our source and perform basic transformations to clean and standardize it."
    columns:
      - name: customer_id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null

      - name: marital_status
        description: "Customer marital status"
        tests:
          - accepted_values:
              arguments:
                values: ["Married", "Single", "n/a"]

      - name: gender
        description: "Customer gender"
        tests:
          - accepted_values:
              arguments:
                values: ["Male", "Female","n/a"]